# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de3750452dd46f34b54ba0fef3b87e770032284e5c1653385557fd4128d8ac711f4bb93824f0f9e8bc685553fa51a44ee2eb6f1a241690542e03c22d731bcb6c

test:
  secret_key_base: 1fccf0ca9ae06b83009ec9dd69d13adad2c5ceb334bfa494d6cf25a5a6c1186998ae403119c62aed12c9305855f453de9e81791a5ebd9b9e91369ad880924d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
